= Andrew Howden
:icons: font
:docinfo: private-head

// Google Analytics
ifdef::backend-html5[]
++++
include::ga.html[]
++++
endif::[]

// Crosslinking
ifdef::backend-pdf[]
TIP: This resume is being regularly updated. An up to date copy is available in HTML at 
     https://www.andrewhowden.com[www.andrewhowden.com] or via downloadable PDF on 
     https://www.andrewhowden.com/media/pdf/resume.pdf[the same website].
endif::[]

ifdef::backend-html5[]
TIP: This resume is being regularly updated. However a printable PDF copy of the current version of this resume can be 
     found https://www.andrewhowden.com/media/pdf/resume.pdf[attached to this website].
endif::[]

[cols="3,8,3,8"]
|===
h| Email     | mailto:hello@andrewhowden.com[hello@andrewhowden.com] h| GitHub    | https://www.github.com/andrewhowdencom/[@andrewhowdencom]
h| Telephone | +49 176 37658815                                      h| LinkedIn  | https://www.linkedin.com/in/andrewhowdencom/[andrewhowdencom]
h| Website   | https://www.andrewhowden.com[www.andrewhowden.com]    h| Twitter   | https://www.twitter.com/@andrewhowdencom[@andrewhowdencom]
|===

== Professional Background

=== Global Fashion Group

[cols="2,8"]
|===
h| Dates    | 2019-04 - 2019-09
h| Location | Berlin, Germany
|===

At Global Fashion Group my responsibilities were as a general software engineer working on the "SellerCenter" product.
This product allowed merchants to list their goods in the GFG venture platforms such as Dafiti, Lamoda, THE ICONIC and
ZALORA.

The product was based on PHP.

==== Achievements

- Replace the CI/CD system "Jenkins CI" with "CircleCI"^cite:[p.circleci]^

=== Sitewards GmbH

[cols="2,8"]
|===
h| Dates    | 2016-10 - 2019-04
h| Location | Frankfurt, Germany
|===


At Sitewards my responsibilities mirrored my responsibilities at Fontis but included a much heavier responsibility
designing and managing the production infrastructure and tooling for these systems.

I worked with several projects all with some eCommerce property including Maschinenring, Schramm, Staedtler, Pluradent
and so on.

==== Achievements

- Designed and implemented the infrastructure, monitoring and deployment definitions of several production e-commerce
  systems.
- Transitioned the company from the monitoring service “New Relic" to the open source “Prometheus”.
- Designed and implemented CI/CD for a variety of PHP, Node, Ansible and static HTML services in both BitBucket 
  Pipelines and Travis CI
- Designed and implemented the “incident response” process used for technical crisis management and resolution.
- Collaborated in the detection and remediation of unauthorized access to a significant service.
- Qualified as a “Certified Kubernetes Administrator”.
- Helped with the organisational understanding of and adjustment to the “General Data Protection Legislation” (GDPR) as
 it applied to Germany.
- Implemented a centralised, community managed knowledge base.
- Evangelised the use, implementation and understanding of various kinds of diagnostic data such as time series, logs, 
  traces and other system introspection tools.
- Helped implement team analytics to determine the health, mood and stress levels of the organisation.
- Developed or contributed to both helm chart and ansible roles for OSQuery and the OSQuery fleet management tool 
  “Kolide Fleet”.
- Organised and chaired development community meetings designed to facilitate knowledge sharing.
- Helped facilitate an employee evaluation and growth framework.
- Debugged countless complex production outages.

=== Fontis PTY LTD

[cols="2,8"]
|===
h| Dates    | 2014-10 - 2016-04
h| Location | Melbourne, Australia
|===

At Fontis my responsibilities were varied and included nearly all aspects of software management. In conjunction
with my time I was responsible for working directly with business partners to design a roadmap for software, the
technical plan for how such software could be implemented, the implementation of that roadmap subject to changing
business requirements and periodically revisiting the technical direction with a view to maximise business return on
invest and finally the production management of that software. 

I worked with several large eCommerce projects including Quiksilver, Bing Lee, Teds and so on.

==== Achievements

- Collaborated in the maintenance, feature development, deployment and management of multi-million dollar e-commerce 
  stores.
- Primarily responsible for several major software migrations, site redesigns and feature developments such as the GAZ 
  MAN redesign, Bing Lee checkout redesign and MageAudit.
- Developed a structure for deploying applications onto Kubernetes continuously, including numerous safety checks.
- Developed a structure for automatically checking the style and quality of code as part of the standard review process.
- Developed provisioning tools that create and manage a Kubernetes cluster that tolerates failure of an application, 
  machine or network partition.
- Developed a template for a JavaScript module that can be loaded by dependency management systems asynchronously.
- Contributed to open source projects such as Ecomdev_CheckItOut, Boilr and Modd.

<<<
== Skills & Knowledge

Specialising in developing open source software related to the development, deployment, monitoring and management of 
internet facing software. List of competencies include:

[cols="2,8"]
|===
h| Software Languages | PHP · HTML · CSS · SASS · Bash · ECMAScript (JavaScript) · Golang · Python · Make · Ruby · 
                        JSON+LD · RDFa · sh · SQL
h| Frameworks         | Magento · Laravel · Symfony · Joolma · Hugo · Bootstrap · PostCSS · Phing · Grunt · Polymer · 
                        RequireJS · Composer · Bower
h| Operating Systems  | Linux · Windows · Debian · Ubuntu · CentOS · Arch · CoreOS
h| Infrastructure     | Docker · Rkt · Kubernetes ·Virtualbox · NGINX · Apache HTTP · Docker Compose · Calico · 
                        Flannel · TravisCI · Jenkins · Netcat · Tcpdump · cURL · Aptitude ·Yum · Picfit
h| Monitoring         | Prometheus · Sensu · Logstash · Beats · Elasticsearch · Kibana · Grafana
h| Testing            | Selenium · Facebook Web Driver · PHPUnit
h| Software Analysis  | PHP · PHPCS · eslint · scss-lint · jsonlint
h| Website Analysis   | Google Analytics · Chrome DevTools · Lighthouse · Google PageSpeed Insights · Qualsys SSL Test
h| Network Protocols  | HTTP/1.1 · HTTP/2 · FastCGI · TCP · UDP · TLS/SSL
h| Cloud Services     | Amazon Web Services · Google Cloud · Let’s Encrypt
h| Security           | Pass · PGP ·GnuPG · OpenSSL · HSTS · CSP · Nmap
h| Development        | Boilr · Intellij IDEs · Atom · Git · Arcanist · Phabricator · GitHub · Request Tracker · Modd · 
                        strace · strings · xdebug · xdd
|===

<<<
== References

bibliography::[]
