language: node_js

branches:
  only:
  - master

addons:
  apt:
    packages:
    - python-docutils
    - git

sudo: required

services:
- docker

env:
- CLOUDSDK_PYTHON_SITEPACKAGES=1
  GIT_SSH_COMMAND="ssh -i .privkey"

before_install:
  - "./build/scripts/lint.sh"
  - "./build/scripts/CI/unpack-secrets.sh"

install:
  - "./build/scripts/CI/install-gems.sh"
  - "./build/scripts/CI/install-dependencies.sh"
  - "./build/scripts/CI/install-sassc.sh"

before_script:
  "./build/scripts/CI/auth.sh"

script:
  - "./build/scripts/CI/deploy.sh"

after_success:
  "./build/scripts/CI/success.sh"

after_failure:
  "./build/scripts/CI/failure.sh"

after_script:
