branches:
  only:
  - master

addons:
  apt:
    packages:
    - python-docutils
    - git

sudo: required

services:
- docker

env:
- CLOUDSDK_PYTHON_SITEPACKAGES=1
  GIT_SSH_COMMAND="ssh -i .privkey"

before_install:
  # General bin
  # Path is ordered this way so we found our custom gcloud prior to travis's one.
  - "PATH=$(pwd)/bin:${PATH}"

  # Google Cloud Path
  - "PATH=$(pwd)/google-cloud-sdk/bin:${PATH}"

  # CI Scripts
  - "PATH=$(pwd)/build/scripts/CI:${PATH}"
  - "./build/scripts/CI/unpack-secrets.sh"

install:
  - "./build/scripts/CI/install-gems.sh"
  - "./build/scripts/CI/install-dependencies.sh"

before_script:
  - "./build/scripts/lint.sh"
  - "./build/scripts/CI/auth.sh"

script:
  - "./build/scripts/CI/deploy.sh"

after_success:
  "./build/scripts/CI/success.sh"

after_failure:
  "./build/scripts/CI/failure.sh"

after_script:
