branches:
  only:
  - master

addons:
  apt:
    packages:
    - python-docutils
    - git

sudo: required

env:
  global:
    - TEST_SUITE=static

services:
- docker

env:
- CLOUDSDK_PYTHON_SITEPACKAGES=1
  GIT_SSH_COMMAND="ssh -i .privkey"

before_install:
  - test $TEST_SUITE = "static" && TEST_FILTER='--filter "Magento\\Test\\Php\\LiveCodeTest"' || true
  - echo "${TEST_FILTER}"
  - "phpunit test.php"
  # General bin
  # Path is ordered this way so we found our custom gcloud prior to travis's one.
  - "export PATH=$(pwd)/bin:${PATH}"

  # Google Cloud Path
  - "export PATH=$(pwd)/google-cloud-sdk/bin:${PATH}"

  # CI Scripts
  - "PATH=$(pwd)/build/scripts/CI:${PATH}"
  - "./build/scripts/CI/unpack-secrets.sh"

install:
  - "./build/scripts/CI/install-dependencies.sh"

before_script:
  - "./build/scripts/lint.sh"
  - "./build/scripts/CI/auth.sh"

script:
  - "make content"
  - "make build-container-nginx"
  - "make push-container-nginx"

after_success:

after_failure:

after_script:
