---
branches:
  only:
    - master

addons:
  apt:
    packages:
      - "git-crypt"

sudo: required

services:
  - docker

env:
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
    GIT_SSH_COMMAND="ssh -i .privkey"

before_install:
  # General bin
  # Path is ordered this way so we found our custom gcloud prior to travis's one.
  - "export PATH=$(pwd)/bin:${PATH}"

  # Google Cloud Path
  - "export PATH=$(pwd)/google-cloud-sdk/bin:${PATH}"

  # CI Scripts
  - "PATH=$(pwd)/build/scripts/CI:${PATH}"
  - "ci/scripts//unpack-secrets.sh"

install:
  - "./ci/scripts/install-dependencies.sh"

before_script:
  - "./ci/scripts/auth.sh"

script:
  - "make content"
  - "make build-container-nginx"
  - "make push-container-nginx"

after_success:

after_failure:

after_script:
