---
dist: xenial

branches:
  only:
    - master

addons:
  apt:
    packages:
      - "git-crypt"

sudo: required

services:
  - docker

env:
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
    GIT_SSH_COMMAND="ssh -i .privkey"

before_install:
  - 'echo "${BASE64_GIT_CRYPT_KEY}" | base64 --decode > ~/.repository-key'
  - 'git-crypt unlock ~/.repository-key'

  # General bin
  # Path is ordered this way so we found our custom gcloud prior to travis's one.
  - "export PATH=$(pwd)/bin:${PATH}"

  # Google Cloud Path
  - 'export PATH="$(pwd)/google-cloud-sdk/bin:${PATH}"'

  # Node path
  - 'export PATH="$(pwd)/node_modules/.bin:${PATH}"'

  # Show path
  - echo "${PATH}"

install:
  - "./ci/scripts/install-dependencies.sh"

before_script:
  - "./ci/scripts/auth.sh"

script:
  - |
      make application.dependencies && \
      make application.content && \
      make container.build.nginx && \
      make container.push.nginx && \
      make deploy

after_success:

after_failure:

after_script:
