FROM littleman/nginx:latest
MAINTAINER littleman.co <support@littleman.co>

ADD build/es6-bundled /var/www/public
ADD deploy/docker/nginx/etc/nginx/sites-enabled/www-andrewhowden-com.conf /etc/nginx/sites-enabled/www-andrewhowden-com.conf
