FROM quay.io/littlemanco/nginx:1.15.7-1
MAINTAINER littleman.co <support@littleman.co>

ADD build/es6-bundled /var/www/public
ADD deploy/docker/nginx/etc/nginx/sites-enabled/www-andrewhowden-com.conf /etc/nginx/sites-enabled/www-andrewhowden-com.conf
