---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: {{ template "web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "web.fullname" . }}
spec:
  hosts:
    - "andrewhowden.com"
    - "www.andrewhowden.com"
  gateways:
   - {{ template "web.fullname" . }}
  http:
  - route:
    - destination:
        port:
          number: 80
        host: {{ template "web.fullname" . }}